apiVersion: v1
kind: Service
metadata:
  name: backend-service # Nginx will proxy to this name
  namespace: cashex
spec:
  selector:
    app: cashex-backend # Routes traffic to backend pods
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP # Internal-only (Nginx proxies to it)
